### PR TITLE
remove augurproject/sdk reference

### LINKED ISSUE #87: Remove dependency on augurproject/sdk package
1. Pull any utils types into a utils package inside the new repo.

### PR DESCRIPTION
**Pull request by andrewdamelio**
@JohnDanz i didn't `yarn remove @augurproject/sdk` yet, wanted to double check with you first we are good to go with that

### CODE REVIEW

**Review by JohnDanz — APPROVED** [review]

**Review by justinbarry — CHANGES_REQUESTED** [review]
Does this remove the sdk package entirely? If so, can we remove it from package.json as well?

**Comment by andrewdamelio** [comment]
> Does this remove the sdk package entirely? If so, can we remove it from package.json as well?

👍

**Review by justinbarry — APPROVED** [review]
LGTM

**Comment by andrewdamelio** [comment]
@JohnDanz @justinbarry looks like removing sdk opens up a bunch of issues further with missing packages in comps (`augurproject/artifacts`, `augurproject/utils`, and other misc dependencies) that were included with the `augurproject/sdk` package

Is it still worth removing from comps @JohnDanz if we need to add a bunch of other dependencies to patch up the missing ones?

**Comment by justinbarry** [comment]
@andrewdamelio Ideally we can move whatever we are using from those package into our monorepo. Depending on what it is.

**Comment by andrewdamelio** [comment]
> @andrewdamelio Ideally we can move whatever we are using from those package into our monorepo. Depending on what it is.

Sounds good -- had to add the below packages
```
+    "async-file": "^2.0.2",
+    "@augurproject/smart": "^1.0.0",
+    "@augurproject/utils": "^2.2.0",
+    "@augurproject/artifacts": "^2.2.0"
```

**Pull request merged**
