### PR TITLE
claimfees and manyfacts

### LINKED ISSUE #223: Creator fees must be claimable
Just sending them doesn't work because if the creator is a contract, it needs a fallback method.

### LINKED ISSUE #224: Deploy and share many market factories
Right now we use one market factory. But we will support arbitrarily man.

### PR DESCRIPTION
**Pull request by robert-e-davidson3**
Large change: The backend now defines multiple deployed market factories at once. This breaks the UI.
Small change: Fees are collected and can be claimed instead of being sent straight out.

### CODE REVIEW

**Comment by robert-e-davidson3** [comment]
Closing to avoid accidentally merging into dev and wrecking UI.

**Review by bthaile — COMMENTED** [review]
lgtm

**Review by bthaile — COMMENTED** [review]
lgtm

**Review by justinbarry — APPROVED** [review]
LGTM

**Pull request merged**
