### PR TITLE
Multi market factories

### LINKED ISSUE #638: Support multiple simultaneous AMMFactory contracts
We need to support multiple AMMFactory addresses to support upgrades.

The idea is for pools created with any AMMFactory to show up and be usable but for any new pools to be created with the new AMMFactory.

This will involve a little bit of backend work to update the addresses.ts file and associated code. Most of the changes will be in the UI however.

QUESTION: How to handle it if a pool exists for multiple AMMFactories at once? This can happen if two users create a pool for the same market using different UI builds, one before the upgrade and one after.

### PR DESCRIPTION
**Pull request by bthaile**
filter out over/under markets from `sportsball` market factory
only include over/under markets from `sportsball2` market factory.

### CODE REVIEW

**Review by JohnDanz — APPROVED** [review]

**Comment by pgebheim** [comment]
This shouldn't really just handle certain market types.

What it needs to do is:
Query Factory1..N for all the markets that are currently available. Always show any market from any those factories that has liquidity. If it is a market with no liquidity, only show for the newest Factory (so that one will be used for creation / resolution).

**Comment by bthaile** [comment]
> This shouldn't really just handle certain market types.
> 
> What it needs to do is:
> Query Factory1..N for all the markets that are currently available. Always show any market from any those factories that has liquidity. If it is a market with no liquidity, only show for the newest Factory (so that one will be used for creation / resolution).

Not following exactly

If I'm reading this correctly. 
Get all markets from all Market factories in the list. 
Sort based on liquidity (always show if there is liquidity)
sort markets based on eventId, show the markets from the priority Market Factory (will configure which is priority, sportsball2)

**Comment by bthaile** [comment]
> This shouldn't really just handle certain market types.
> 
> What it needs to do is:
> Query Factory1..N for all the markets that are currently available. Always show any market from any those factories that has liquidity. If it is a market with no liquidity, only show for the newest Factory (so that one will be used for creation / resolution).

If I'm reading this correctly. 
Get all markets from all Market factories in the list. 
(Show all markets that have liquidity)
Filter out markets in sportsball2 that are shown from sportsball (these had liquidity). Show all other sportsball2 markets.

**Comment by bthaile** [comment]
Made changes to only take markets that have or had liquidity from sportsball market factory then take all the rest from sportsball2.

**Pull request merged**
